### PR TITLE
Row style widgets to match gdoc spec

### PR DESCRIPTION
**Pull request by AchizuePriscilla**

### CODE REVIEW

**Comment by yougane** [comment]
Hello @AchizuePriscilla, I noticed that you reverted [some changes](https://github.com/NewMillennialGames/st_event_config_cli/pull/18/files#diff-7244bc8300cde1e40e8343cdeeabdeb2cfcd64c31968294b125a7bc6f7164a89L103-R98) I made to fix the state of Trade button. Is this intentional?

**Comment by AchizuePriscilla** [comment]
@yougane it isn't intentional at all, I think it got reverted during a merge

**Comment by yougane** [comment]
I see. I'll revert it back :)

**Comment by yougane** [comment]
@AchizuePriscilla I reverted it back again but there are other compilation errors. I think something else broke when you merged master into this branch.

**Comment by AchizuePriscilla** [comment]
Could you try upgrading the stclient dependency and running the build_runner too? That usually fixes most of my compilation errors

**Comment by yougane** [comment]
@AchizuePriscilla I already have the latest stclient version. As you can see [here](https://github.com/NewMillennialGames/st_event_config_cli/blob/d7a15e875ed8d6937b86b73212ab3b6ec1f946ed/st_ui_builder/lib/ui_builder/row_style_widgets.dart#L338-L341), CompetitorImage is given an `isTwoAssetRow` argument, but [CompetitorImage](https://github.com/NewMillennialGames/st_event_config_cli/blob/d7a15e875ed8d6937b86b73212ab3b6ec1f946ed/st_ui_builder/lib/ui_builder/shared_row_components.dart#L39-L43) doesn't accept an `isTwoAssetRow` parameter. That's the error I get.

**Comment by AchizuePriscilla** [comment]
@yougane It seems the shared row components file was omitted during my initial commit. I just pushed my local version. It contains the necessary fix

**Comment by yougane** [comment]
Thank you! It's working now.

**Pull request merged**
